
services:
 
  app:
    image: ${REPO_NAME}/fsloader:1.0.0
    container_name: app
    hostname: app
    depends_on:
      - mongodb
    environment:
      ECHOCONFIG: ${ECHOCONFIG}
      DEBUGLEVEL: ${DEBUGLEVEL}
      ECHORECORDS: ${ECHORECORDS}
      FLUSHCAP: ${FLUSHCAP}
      RECCAP: ${RECCAP}
      SOURCEPATHS: ${SOURCEPATHS}
      DEST: ${DEST}

      MONGO_ROOT: ${MONGO_ROOT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DIRECT: ${MONGO_DIRECT}
      MONGO_DATASTORE: ${MONGO_DATASTORE}          
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_BATCH_SIZE: ${MONGO_BATCH_SIZE}
    profiles:
      - donotstart

  # Used to test the local Kafka Connector/sinks into MongoDB or direct insert into MongoDB Collection.
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
    # profiles:
    #   - donotstart


# Without a network explicitly defined, you hit this Hive/Thrift error
# java.net.URISyntaxException Illegal character in hostname
# https://github.com/TrivadisPF/platys-modern-data-platform/issues/231
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
